Create owner cap management
eluv-io/elv-fabric-browser pull request #21
Opened 2021-11-19 01:21 UTC by elv-zenia

Create section within Content Object Info that allows the owner to add and delete owner caps.

![Screen Shot 2021-11-16 at 9 59 51 AM](https://user-images.githubusercontent.com/91760982/142525665-c78982ab-d9cd-40de-bb30-98ce151ed6e2.png)
![Screen Shot 2021-11-18 at 3 45 04 PM](https://user-images.githubusercontent.com/91760982/142525710-6ddefc81-df6e-44c8-9779-e40188d2d860.png)

https://user-images.githubusercontent.com/91760982/142531271-a7a1dae5-e6d3-4573-bdf8-b3f6c6493301.mov

Expected/Tested
- Do not show current user cap within Advanced section
- Show advanced section to owner only
- Users with owner cap and view/manage permissions can download/upload encrypted files
- User with view permission and no owner cap still able to access but not upload/download
- Throw error if attempting to create an owner cap before owner has a user cap

Relates to #9 

See Client PR: https://github.com/eluv-io/elv-client-js/pull/129
See Core PR: https://github.com/eluv-io/elv-core-js/pull/25

2021-11-19 21:52 UTC, elv-kevin requested changes
The code all looks good to me, but I think we should present this differently in the UI.

Instead of calling the section 'Advanced', call it 'Encryption Keys'. Users don't really need to know about the ugly details of how they work, and no one except us knows what caps are.

What we want to present is this: Here are the list of users that have encryption access to this object. If you're the owner, you can add or remove users. Non owners should be able to see this list but not modify it.

I think we should also add a name field for the users. Unfortunately for stupid reasons, users are not allowed to access other user's metadata, even if it's public, so we can't get the name automatically. That means we'll have to take it in the form.

You can save that info somewhere in the metadata as part of saving the owner cap, maybe something like /cap_owners, just a map of user address to name. Then you can use that info to display the list of users who have access. You'll probably want to modify the CreateOwnerCap method to either take a write token and not do finalize if provided (like we did with another method) so that you can make this modification along with the cap creation in one commit.

I think the order of the form should be name, address, public key, and the list of user keys should just be name and address (0x address, not iusr)

Finally, for the public key textarea, there's a parameter on LabelledField in the fabric browser called `alignTop`, that will make the label sit at the top of the textarea instead of in the middle.

2021-11-23 01:58 UTC, elv-zenia commented
@elv-kevin Updated

2021-11-24 20:16 UTC, elv-kevin reviewed
Sorry to keep going back and forth on this, but the UI is still not there yet.

Main issue at the moment is that there's no indentation to indicate the particular keys belong to the 'encryption keys' section.

I think the list of keys would be better represented as a table: name, address, delete button

```
| Name | Address    |     |
| User1 | 0x.......       | X |
| User2 | 0x.......      |  X  |
```
actual HTML tables are a pain in the ass to work with in CSS, so I usually just make them out of divs with display: grid. in this case, you can just do grid-template-columns: 1fr 2fr 50px. Probably keep the buttons visible but disabled if the user is not allowed to delete.

Additionally, since this thing expands, let's move it to the bottom, below the permissions selection, and move the version cound up to below the owner address.

2021-11-24 20:16 UTC, elv-kevin commented on src/components/pages/content/ContentObject.js
> +          {Object.keys(this.props.objectStore.object.meta.owner_caps).map(capAddress => (
this fails if owner_caps is undefined. Always have a fallback initialization on things like .map or Object.keys()

2021-11-24 20:16 UTC, elv-kevin commented on src/components/pages/content/ContentObject.js
> +            onClick={() => this.DeleteCap(capAddress)}
capAddress is undefined at this point and throws an error

2021-11-29 21:42 UTC, elv-zenia commented
@elv-kevin Updated with a table for the keys section. Let me know what you think.

2021-11-29 22:06 UTC, elv-kevin commented
Almost there, couple things about the table:
- limit the width, it gets very wide and hard to read with a wide screen. 700px should be fine. 
- indent the table so it's clearly under the encryption keys label
- vertical align the cells. you can do this by evening out the padding, e.g. by adding `div { padding: 5px 10px; }` to the body-row and header-row defs. This will also add padding to the body rows which I think will look better
- remove 'Delete' from the header and just leave it blank.
- center the delete icons (you can either give their cell a class and `justify-content: center` or `display:block; margin: auto` on the button

2021-11-29 23:02 UTC, elv-zenia commented
@elv-kevin Updated

2021-11-29 23:27 UTC, elv-kevin commented
Almost

By indented I meant indented as much as the labelled fields are. the encryption key buttons should be left aligned with the left edge of the table

Can you also do something to differentiate the header from the rest of the table? Maybe make the text bold or make the background light gray.

And I think we should also add the owner key as well. Owner for the name, not deletable

2021-11-30 04:29 UTC, elv-zenia commented
@elv-kevin Updated

![image](https://user-images.githubusercontent.com/91760982/143985757-a83f59d5-aa40-48d6-bf47-6875085a2916.png)

2021-11-30 19:34 UTC, merged