clarified README and configuration-example
eluv-io/elv-fabric-browser pull request #44
Opened 2022-06-20 17:51 UTC by elv-seth

2022-06-20 18:05 UTC, elv-kevin requested changes

2022-06-20 18:05 UTC, elv-kevin commented on README.md
> +- Clone this repo along with ```elv-core-js```, and ```elv-client-js``` projects from github
You don't need to clone elv-client-js, that's just included as a dependency.

2022-06-20 18:05 UTC, elv-kevin commented on configuration-example.js
> +  // Fabric Network
this and the readme need details on
`fabricBrowserApps`,
`displayAppUrl`,
`embedAppUrl`

see https://core.v3.contentfabric.io/configuration.js for defaults

2022-06-20 18:07 UTC, elv-kevin commented on configuration-example.js
> +  // Fabric Network
Please also specify that `coreUrl` should be changed to `http://localhost:8082` (local core url).

2022-06-20 18:11 UTC, elv-kevin commented on README.md
> +- Open the newly created ```configuration.js``` file and comment out all the config-url’s except for the one you wish to use (main, demo or test). Note that the config-url in elv-fabric-browser must
Maybe rephrase it as 'all instances of `config-url`'

2022-06-21 16:38 UTC, elv-seth commented on README.md
>  - Open [http://localhost:8082](http://localhost:8082) in your browser
Including lines 13 and 14 where we specify the npm commands to run?

2022-06-28 21:42 UTC, elv-kevin requested changes
Noted last couple of changes we need.

Please also add a note about modifying Core's config to add the local fabric browser to `apps`

2022-06-28 21:42 UTC, elv-kevin commented on configuration-example.js
> +  // Fabric Browser
remove this comment (`// Fabric browser`)

2022-06-28 21:42 UTC, elv-kevin commented on configuration-example.js
> +  "config-url": "https://test.net955203.contentfabric.io/config",
after looking at the code, fabric browser doesn't actually need config-url  so we can remove that from the config and references to it from the readme.

2022-06-28 21:42 UTC, elv-kevin commented on configuration-example.js
> +  // manageAppUrl
Uncomment these default app urls, they're necessary for the app to function.

2022-06-29 20:06 UTC, merged